---
- name: Deploy MongoDB
  import_playbook: deploy_mongodb.yml

- name: Deploy 4G Core
  import_playbook: deploy_4g.yml

- name: Deploy 5G Core
  import_playbook: deploy_5g.yml

- name: Deploy User Plane
  import_playbook: deploy_userplane.yml
