mcc: "999"
mnc: "70"

nci: "0x000000010"
idLength: 32
tac: 1

linkIp: 10.10.0.100 # RAN VM IP
ngapIp: 10.10.0.100 # RAN VM IP
gtpIp: 10.10.0.100 # RAN VM IP

amfConfigs:
  - address: 10.10.0.2 # Control Plane VM IP
    port: 38412

slices:
  - sst: 1
    sd: 0x000001
  - sst: 2
    sd: 0x000002

ignoreStreamIds: true
